name: CI  
  
# 控制工作流何时运行  
on:  
  # 当代码被推送到main分支时触发（可选，根据需要保留或删除）  
  push:  
    branches: ["main"]  
  
  # 手动触发  
  workflow_dispatch:  
  
  # 每天凌晨0点触发  
  schedule:  
    - cron: '0 0 * * *'  
  
# 工作流包含一个或多个作业  
jobs:  
  # 这个工作流包含一个名为build的作业  
  build:  
    # 作业在ubuntu-latest上运行  
    runs-on: ubuntu-latest  
  
    name: generate-github-profile-3d-contrib  
  
    # 作业执行的步骤  
    steps:  
      # 检出仓库  
      - uses: actions/checkout@v3  
  
      # 使用yoshi389111/github-profile-3d-contrib Action生成3D贡献图  
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          USERNAME: ${{ github.repository_owner }}  
  
      # 提交并推送更改到仓库  
      - name: Commit & Push  
        run: |  
          git config user.name github-actions  
          git config user.email github-actions@github.com  
          git add -A .  
          # 仅在存在更改时才提交  
          if git diff-index --quiet HEAD --; then  
            echo "No changes to commit"  
          else  
            git commit -m "Update 3D GitHub contribution graph [$(date +'%Y-%m-%d')]"  
            git push  
          fi
