name: Update GitHub Activity

on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update GitHub Activity
        uses: TheDanniCraft/activity-log@v1
        with:
          GITHUB_USERNAME: "oceanhhan"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EVENT_LIMIT: 8
          HIDE_DETAILS_ON_PRIVATE_REPOS: true
          EVENT_EMOJI_MAP: |
            PushEvent: "⬆️"
            CreateEvent: "✨"
            DeleteEvent: "🔥"
            IssuesEvent: |
              opened: "🆕"
              closed: "✅"
